# Generated by Django 4.1.7 on 2023-03-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=35)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Estado', models.CharField(max_length=35)),
                ('foto', models.URLField(max_length=300)),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.marca')),
            ],
        ),
    ]
