# Generated by Django 4.1.7 on 2023-03-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Marca',
            new_name='marca',
        ),
    ]
