# Generated by Django 4.1.7 on 2023-04-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_marca_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Descripcion',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='producto',
            name='NombreProducto',
            field=models.CharField(max_length=70),
        ),
    ]
