# Generated by Django 4.1.7 on 2023-04-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
