# Generated by Django 4.1.7 on 2023-04-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_tag_producto_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tag',
        ),
    ]
