# Generated by Django 4.1.7 on 2023-04-08 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_remove_producto_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Store.tag'),
            preserve_default=False,
        ),
    ]
