# Generated by Django 4.1.7 on 2023-04-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_remove_producto_categoria_tag_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Descripcion2',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
